FROM node:14.16.0 as building_production
WORKDIR /usr/src/
COPY ["package.json", "package-lock.json",  "/usr/src/"]
RUN npm install --only=production
COPY [".", "/usr/src/"]
RUN npm run build

FROM nginx:stable-alpine
COPY --from=building_production ["/usr/src/build/", "/usr/share/nginx/html/"]
COPY ["./prod/default.conf" , "/etc/nginx/conf.d/default.conf"]
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]   