name: Deploy
on:
  push:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building image
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build

    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: "minecraftLegionWebClientArtifact"
          path: ${{ env.DOTNET_ROOT }}/client